#include "providers_defines.h"

// #define ENABLE_IR_PROVIDER

#define INPUTS_COUNT 8
#define OUTPUTS_COUNT 8

#define TEMP_SENSORS_COUNT 8
// #define TEMP_UPDATE_INTERVAL 1000

#define TEMP_SENSORS_MODES { INTFRAC, INTFRAC, INTFRAC, INTFRAC, \
	INTFRAC, INTFRAC, INTFRAC, INTFRAC }
