#include "advinputmanager_avr.h"

#define led PORTD,5

#define out1 PORTC,0
#define out2 PORTC,1
#define out3 PORTC,2
#define out4 PORTC,3
#define out5 PORTC,4
#define out6 PORTC,5
#define out7 PORTD,0
#define out8 PORTD,1

#define in1 PORTD,6
#define in2 PORTD,7
#define in3 PORTB,0
#define in4 PORTB,1
#define in5 PORTB,2
#define in6 PORTB,3
#define in7 PORTB,4
#define in8 PORTB,5

// #define ADVIM_DEBUG
#define ADVIM_INPUTSCOUNT 8
#define ADVIM_PATTERNMAX 20

#define ADVIM_INPUT0_ADDR in1
#define ADVIM_INPUT0_FLAGS 0
#define ADVIM_INPUT0_DEBOUNCETIME 5
#define ADVIM_INPUT0_PATTERNTIMEOUT 0

#define ADVIM_INPUT1_ADDR in2
#define ADVIM_INPUT1_FLAGS 0
#define ADVIM_INPUT1_DEBOUNCETIME 5
#define ADVIM_INPUT1_PATTERNTIMEOUT 0

#define ADVIM_INPUT2_ADDR in3
#define ADVIM_INPUT2_FLAGS 0
#define ADVIM_INPUT2_DEBOUNCETIME 5
#define ADVIM_INPUT2_PATTERNTIMEOUT 0

#define ADVIM_INPUT3_ADDR in4
#define ADVIM_INPUT3_FLAGS 0
#define ADVIM_INPUT3_DEBOUNCETIME 5
#define ADVIM_INPUT3_PATTERNTIMEOUT 0

#define ADVIM_INPUT4_ADDR in5
#define ADVIM_INPUT4_FLAGS 0
#define ADVIM_INPUT4_DEBOUNCETIME 5
#define ADVIM_INPUT4_PATTERNTIMEOUT 0

#define ADVIM_INPUT5_ADDR in6
#define ADVIM_INPUT5_FLAGS 0
#define ADVIM_INPUT5_DEBOUNCETIME 5
#define ADVIM_INPUT5_PATTERNTIMEOUT 0

#define ADVIM_INPUT6_ADDR in7
#define ADVIM_INPUT6_FLAGS 0
#define ADVIM_INPUT6_DEBOUNCETIME 5
#define ADVIM_INPUT6_PATTERNTIMEOUT 0

#define ADVIM_INPUT7_ADDR in8
#define ADVIM_INPUT7_FLAGS 0
#define ADVIM_INPUT7_DEBOUNCETIME 5
#define ADVIM_INPUT7_PATTERNTIMEOUT 0
