#include "providers_defines.h"

#define INPUTS_COUNT 16
#define OUTPUTS_COUNT 16

#define TEMP_SENSORS_COUNT 0

#define OUTPUT_PROVIDER_ENABLED
#define INPUT_PROVIDER_ENABLED
#define IR_PROVIDER_ENABLED
#define TEMP_PROVIDER_ENABLED

#define TEMP_SENSORS_MODES { INTFRAC, INTFRAC, INTFRAC, INTFRAC, \
	INTFRAC, INTFRAC, INTFRAC, INTFRAC }

