#include "providers_defines.h"

#define INPUTS_COUNT 16
#define OUTPUTS_COUNT 16

#define TEMP_SENSORS_COUNT 1

#define TEMP_SENSOR0_MODE INTFRAC

#define TEMP_SENSOR1_MODE  FLOAT
#define TEMP_SENSOR2_MODE  INTFRAC
#define TEMP_SENSOR3_MODE  INTFRAC
#define TEMP_SENSOR4_MODE  INTFRAC
#define TEMP_SENSOR5_MODE  INTFRAC
#define TEMP_SENSOR6_MODE  INTFRAC
#define TEMP_SENSOR7_MODE  INTFRAC
#define TEMP_SENSOR8_MODE  INTFRAC
#define TEMP_SENSOR9_MODE  INTFRAC
#define TEMP_SENSOR10_MODE INTFRAC
#define TEMP_SENSOR11_MODE INTFRAC
#define TEMP_SENSOR12_MODE INTFRAC
#define TEMP_SENSOR13_MODE INTFRAC
#define TEMP_SENSOR14_MODE INTFRAC
#define TEMP_SENSOR15_MODE INTFRAC
